name: new-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    # inputs:
    #   parameter_name:
    #     description: 'Description of your parameter'
    #     required: true
    #     default: 'default_value'
jobs:
  Deploy:
    runs-on: self-hosted
    environment:
      name: dev
    steps:
      - name: Call Share Action from another repository
        uses: Beezzbank/action-lab/.github/actions@main 
        with:
          HOST_IP: ${{ vars.HOST_IP }}
          
      - name: Check
        run: |
          echo "HOST_IP from Action: $result"